name: Build Project

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Enable corepack
        run: |
          corepack enable
          corepack prepare yarn@3.6.3 --activate
          yarn set version 3.6.3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install
        run: |
          yarn

      - name: Build
        run: |
          yarn build
