on:
  pull_request:
    branches: [ "main" ]

jobs:
  commitlint:
    uses: ./.github/workflows/commitlint.yml
    secrets: inherit
  build:
    needs: commitlint
    uses: ./.github/workflows/build.yml
    secrets: inherit
